# This is a hack to make sure the bootstrp directory
# exists, and that wmake can be run in it without passing
# additional arguments
# TODO: The POSIX build should be split to separate the
# library and utilities
!include ../bootmake
